- hosts: localhost
  gather_facts: yes
  become: true
  connection: local
  tasks:
    - name: Get EC2 instances with instancemode:node
      amazon.aws.ec2_instance_info:
        region: "us-west-2"
        filters:
          "tag:instancemode": "node"
      register: ec2_facts

    - name: Debug EC2 instance public DNS
      debug:
        var: ec2_facts.instances[0].public_dns_name

    - name: Add EC2 IPs to node inventory file
      lineinfile:
        path: ./nodeinv
        line: "{{ item.public_dns_name }}"
      loop: "{{ ec2_facts.instances }}"

    - name: Add [kubenodes:vars] section
      lineinfile:
        path: ./nodeinv
        line: "[kubenodes:vars]"

    - name: Add ansible_user line
      lineinfile:
        path: ./nodeinv
        line: "ansible_user=ubuntu"

    - name: Add ansible_ssh_private_key_file line
      lineinfile:
        path: ./nodeinv
        line: "ansible_ssh_private_key_file=/var/lib/jenkins//var/lib/jenkins/kubecusteradmin"

    - name: Add ansible_ssh_common_args line
      lineinfile:
        path: ./nodeinv
        line: "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"

    - name: Upload node inventory file to S3
      amazon.aws.s3_object:
        region: "us-west-2"
        bucket: "{{ lookup('env', 'ANSIBLE_BUCKET_NAME') }}"
        mode: put
        object: nodeinv
        src: ./nodeinv